---
# This code developed by Zalina

- name: Create New VLAN Interface 2 on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-01 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create New VLAN Interface 2 on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-02 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create Broadcast Domain for VLAN 2
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port broadcast-domain create -broadcast-domain {{ bd_vlan2 }} -mtu 1500 -ports {{ cluster_name | upper }}-01:a0a-{{ vlan2 }}, {{ cluster_name | upper }}-02:a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create SVM using ansible
  na_ontap_svm:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "{{ svm_name | lower }}"
    subtype             : default
    root_volume         : "{{ svm_name | lower }}_root"
    root_volume_aggregate: "{{ aggr_b_data1 }}"
    root_volume_security_style: unix
    language            : c.utf_8
    snapshot_policy     : default
    ipspace             : Default
    comment             : NFS primary with multi-protocol CIFS
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create NFS SVM MGMT LIF using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["network interface create -vserver {{ svm_name | lower }} -lif {{ svm_name | lower }}_mgmt -role data -data-protocol none -home-node {{ cluster_name }}-02 -home-port a0a-{{ vlan2 }} -address {{ svm_ip_m }} -netmask {{ svm_netmask }} -status-admin up -failover-policy broadcast-domain-wide -firewall-policy mgmt -auto-revert true -failover-group {{ failover_group }}"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Configure NFS SVM node A LIF using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "network interface create -vserver {{ svm_name | lower }} -lif {{ svm_name | lower }}_cifs_nfs_lif01 -role data -data-protocol cifs,nfs -address {{ svm_lif1_ip }} -netmask {{ svm_netmask }} -home-port a0a-{{ vlan2 }} -home-node {{ cluster_name | upper }}-01 -auto-revert true -failover-policy broadcast-domain-wide -firewall-policy data -failover-group {{ failover_group }} -status-admin up " ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Configure NFS SVM node B LIF using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "network interface create -vserver {{ svm_name | lower }} -lif {{ svm_name | lower }}_cifs_nfs_lif02 -role data -data-protocol cifs,nfs -address {{ svm_lif2_ip }} -netmask {{ svm_netmask }} -home-port a0a-{{ vlan2 }} -home-node {{ cluster_name | upper }}-02 -auto-revert true -failover-policy broadcast-domain-wide -firewall-policy data -failover-group {{ failover_group }} -status-admin up " ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Enable NFS on SVM
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "nfs create -vserver {{ svm_name }} -access true -v3 enabled -v4.1 enabled -vstorage enabled -showmount enabled" ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Setup NIS on SVM (Not Compulsary)
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "vserver services name-service nis-domain create -vserver {{ svm_name }} -domain {{ nis_domain }} -active true -servers {{ nis_ip }}" ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Enable 64bit Identifiers on NFSv3
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : "set,adv,-confirmations,off,;,nfs,server,modify,-vserver,{{ svm_name | lower }},-v3-64bit-identifiers,enabled"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Enable 64bit Identifiers on NFSv4
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : "set,adv,-confirmations,off,;,nfs,server,modify,-vserver,{{ svm_name | lower }},–v4-64bit-identifiers,enabled"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Modify NSSWITCH - Passwd DB
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "vserver services name-service ns-switch modify -vserver {{ svm_name }} -database passwd -sources files,nis" ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Modify NSSWITCH - Netgroup DB
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "vserver services name-service ns-switch modify -vserver {{ svm_name }} -database netgroup -sources files,nis" ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Modify NSSWITCH - Group DB
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "vserver services name-service ns-switch modify -vserver {{ svm_name }} -database group -sources files,nis" ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local