---
# - name: login
#   na_ontap_info         :
#     state               : info
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local
#   register: ontap_info

# - name: Show FC vserver
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [ 'lun portset show -instance -protocol fcp']
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local
#   register              : vserver_fcp

# - name: show result of vserver fcp
#   debug:
#     msg: "{{ vserver_fcp.msg }}"

- name: Create FC SVM data LIF Node A
  na_ontap_interface:
    state: present
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    vserver             : "{{ vserverfc_name }}"
    interface_name      : "{{ svmfc_lif_nodea }}"
    role                : data
    protocols           : fcp
    home_port: "{{ homeport }}"
    home_node: "{{ nodea_name }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
  #register              : svm_lif_result

- name: Create FC SVM data LIF Node B
  na_ontap_interface:
    state: present
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    vserver             : "{{ vserverfc_name }}"
    interface_name      : "{{ svmfc_lif_nodeb }}"
    role                : data
    protocols           : fcp
    home_port: "{{ homeport }}"
    home_node: "{{ nodeb_name }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add Portset on Node A
  na_ontap_portset:
    state               : present
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    vserver             : "{{ vserverfc_name }}"
    name                : "{{ portset_name }}"
    ports               : "{{ svmfc_lif_nodea }}"
    type                : fcp

- name: Add Portset on Node B
  na_ontap_portset:
    state               : present
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    vserver             : "{{ vserverfc_name }}"
    name                : "{{ portset_name }}"
    ports               : "{{ svmfc_lif_nodeb }}"
    type                : fcp
