
- name: broadcast domain remove ports from Default
  na_ontap_broadcast_domain_ports:
    state: absent
    broadcast_domain: Default
    ports: ["{{ cluster_name }}-01:{{ item }}", "{{ cluster_name }}-02:{{ item }}"]
    hostname: "{{ cluster_name }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    ontapi: 32
    https: true
    validate_certs: false
  connection: local
  with_items:
    - "{{ porta | default([]) }}"
    - "{{ portb | default([]) }}"
    - "{{ portc | default([]) }}"
    - "{{ portd | default([]) }}"

- name: Create ifgrp on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp create -node {{ cluster_name | upper }}-01 -ifgrp a0a -mode multimode_lacp -distr-func port']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add port to ifgrp on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp add-port -node {{ cluster_name | upper }}-01 -ifgrp a0a -port {{ item }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
  with_items:
    - "{{ porta | default([]) }}"
    - "{{ portb | default([]) }}"
    - "{{ portc | default([]) }}"
    - "{{ portd | default([]) }}"

- name: Create ifgrp on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp create -node {{ cluster_name | upper }}-02 -ifgrp a0a -mode multimode_lacp -distr-func port']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add port to ifgrp on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp add-port -node {{ cluster_name | upper }}-02 -ifgrp a0a -port {{ item }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
  with_items:
    - "{{ porta | default([]) }}"
    - "{{ portb | default([]) }}"
    - "{{ portc | default([]) }}"
    - "{{ portd | default([]) }}"

- name: Create VLAN Interface 1 on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-01 -vlan-name a0a-{{ vlan1 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create VLAN Interface 1 on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-02 -vlan-name a0a-{{ vlan1 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create VLAN Interface 2 on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-01 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create VLAN Interface 2 on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-02 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create Broadcast Domain for VLAN 1
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port broadcast-domain create -broadcast-domain {{ bd_vlan1 }} -mtu 1500 -ports {{ cluster_name | upper }}-01:a0a-{{ vlan1 }}, {{ cluster_name | upper }}-02:a0a-{{ vlan1 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create Broadcast Domain for VLAN 2
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port broadcast-domain create -broadcast-domain {{ bd_vlan2 }} -mtu 1500 -ports {{ cluster_name | upper }}-01:a0a-{{ vlan2 }}, {{ cluster_name | upper }}-02:a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Update LIF for Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network interface modify -vserver {{ cluster_name | upper }} -lif {{ cluster_name }}-02_mgmt -home-node {{ cluster_name | upper }}-02 -home-port a0a-{{ vlan1 }} -auto-revert true -failover-group {{ bd_vlan1 }} ']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Update LIF for Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network interface modify -vserver {{ cluster_name | upper }} -lif {{ cluster_name }}-01_mgmt -home-node {{ cluster_name | upper }}-01 -home-port a0a-{{ vlan1 }} -auto-revert true -failover-group {{ bd_vlan1 }} ']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Update LIF for cluster_mgmt
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network interface modify -vserver {{ cluster_name | upper }} -lif cluster_mgmt -home-node {{ cluster_name | upper }}-01 -home-port a0a-{{ vlan1 }} -auto-revert true -failover-group {{ bd_vlan1 }} ']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create ICL LIF Node A using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["network interface create -vserver {{ cluster_name | upper }} -lif {{ cluster_name | lower }}-01icl1 -role intercluster -home-node {{ cluster_name | upper }}-01 -home-port a0a-{{ vlan1 }} -address {{ icl_a_ip}} -netmask {{ vlan1_netmask }} -status-admin up -failover-policy local-only -firewall-policy intercluster -auto-revert false -failover-group {{ bd_vlan1 }}"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create ICL LIF Node B using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["network interface create -vserver {{ cluster_name | upper }} -lif {{ cluster_name | lower }}-02icl1 -role intercluster -home-node {{ cluster_name | upper }}-02 -home-port a0a-{{ vlan1 }} -address {{ icl_b_ip}} -netmask {{ vlan1_netmask }} -status-admin up -failover-policy local-only -firewall-policy intercluster -auto-revert false -failover-group {{ bd_vlan1 }}"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: NTP 1 using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["cluster time-service ntp server create -server 131.126.135.7"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: NTP 2 using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["cluster time-service ntp server create -server 131.126.135.6"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: NTP 3 using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["cluster time-service ntp server create -server 198.43.1.15"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: NTP 4 using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["cluster time-service ntp server create -server 198.43.1.14"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
