
- name: broadcast domain remove ports from Default
  na_ontap_broadcast_domain_ports:
    state: absent
    broadcast_domain: Default
    ports: ["{{ nodea_name }}:{{ item }}", "{{ nodeb_name }}:{{ item }}"]
    hostname: "{{ cluster_name }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    ontapi: 32
    https: true
    validate_certs: false
  connection: local
  with_items:
    - "{{ porta | default([]) }}"
    - "{{ portb | default([]) }}"
    - "{{ portc | default([]) }}"
    - "{{ portd | default([]) }}"

- name: Create ifgrp on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp create -node {{ cluster_name | upper }}-01 -ifgrp a0a -mode multimode_lacp -distr-func port']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add port to ifgrp on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp add-port -node {{ cluster_name | upper }}-01 -ifgrp a0a -port {{ item }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
  with_items:
    - "{{ porta | default([]) }}"
    - "{{ portb | default([]) }}"
    - "{{ portc | default([]) }}"
    - "{{ portd | default([]) }}"

- name: Create ifgrp on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp create -node {{ cluster_name | upper }}-02 -ifgrp a0a -mode multimode_lacp -distr-func port']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add port to ifgrp on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port ifgrp add-port -node {{ cluster_name | upper }}-02 -ifgrp a0a -port {{ item }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
  with_items:
    - "{{ porta | default([]) }}"
    - "{{ portb | default([]) }}"
    - "{{ portc | default([]) }}"
    - "{{ portd | default([]) }}"

- name: Create VLAN Interface 1 on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-01 -vlan-name a0a-{{ vlan1 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create VLAN Interface 1 on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-02 -vlan-name a0a-{{ vlan1 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create VLAN Interface 2 on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-01 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create VLAN Interface 2 on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-02 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create Broadcast Domain for VLAN 1
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port broadcast-domain create -broadcast-domain {{ bd_vlan1 }} -mtu 1500 -ports {{ cluster_name | upper }}-01:a0a-{{ vlan1 }}, {{ cluster_name | upper }}-02:a0a-{{ vlan1 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create Broadcast Domain for VLAN 2
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port broadcast-domain create -broadcast-domain {{ bd_vlan2 }} -mtu 1500 -ports {{ cluster_name | upper }}-01:a0a-{{ vlan2 }}, {{ cluster_name | upper }}-02:a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Update LIF for Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network interface modify -vserver {{ cluster_name | upper }} -lif {{ cluster_name }}-02_mgmt -home-node {{ cluster_name | upper }}-02 -home-port a0a-{{ vlan1 }} -auto-revert true -failover-group {{ bd_vlan1 }} ']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Update LIF for Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network interface modify -vserver {{ cluster_name | upper }} -lif {{ cluster_name }}-01_mgmt -home-node {{ cluster_name | upper }}-01 -home-port a0a-{{ vlan1 }} -auto-revert true -failover-group {{ bd_vlan1 }} ']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Update LIF for cluster_mgmt
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network interface modify -vserver {{ cluster_name | upper }} -lif cluster_mgmt -home-node {{ cluster_name | upper }}-01 -home-port a0a-{{ vlan1 }} -auto-revert true -failover-group {{ bd_vlan1 }} ']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local