
- name: Modify CIFS Options 1
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : "set,advanced,-confirmations,off,;,vserver,cifs,options,modify,-vserver,{{ svm_name | lower }},-max-mpx,1124"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Modify CIFS Options 2
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : "set,advanced,-confirmations,off,;,vserver,cifs,options,modify,-vserver,{{ svm_name | lower }},-smb2-enabled,true"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Modify CIFS Security
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : "set,advanced,-confirmations,off,;,vserver,cifs,security,modify,-vserver,{{ svm_name | lower }},-is-signing-required,false"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

# - name: Create FSAAPermission Role with access READONLY
#   na_ontap_user_role:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     state               : present
#     name                : FSAAPermission
#     command_directory_name: vserver cifs share show
#     access_level        : readonly
#     query               : show
#     vserver             : "{{ svm_name | lower }}"
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local

- name: Create role 1
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'security login role create -role FSAAPermission -vserver {{ svm_name | lower }} -access readonly -cmddirname version' ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create role 2
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'security login role create -role FSAAPermission -vserver {{ svm_name | lower }} -access readonly -cmddirname "vserver cifs share show" ' ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create role 3
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'security login role create -role FSAAPermission -vserver {{ svm_name | lower }} -access readonly -cmddirname "vserver fpolicy" ' ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create role 4
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'security login role create -role FSAAPermission -vserver {{ svm_name | lower }} -access readonly -cmddirname "volume show" ' ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create role 5
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'security login role create -role FSAAPermission -vserver {{ svm_name | lower }} -access readonly -cmddirname "security login rol show-ontapi" ' ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

# - name: Add User per security model
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [' security login create -user-or-group-name "{{ domain_name.split(".")[0] }}\\xsStealthAUDITProxy" -application ontapi -authentication-method domain -role FSAAPermission -vserver {{ svm_name | lower }}"]
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local

- name: Add User 1 in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "{{ domain_name.split('.')[0] }}\\xsStealthAUDITProxy"
    applications        : ontapi
    authentication_method: domain
    role_name           : FSAAPermission
    vserver             : "{{ svm_name | lower }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add User 2 in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "NA\\xsCVbackup"
    applications        : ontapi
    authentication_method: domain
    role_name           : vsadmin
    vserver             : "{{ svm_name | lower }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local


- name: Add member to CIFS local group
  na_ontap_cifs_local_group_member:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    vserver             : "{{ svm_name | lower }}"
    group               : BUILTIN\Administrators
    member              : 
      - "{{svm_name | lower }}\\Administrator"
      - UPSTREAMACCTS\P-UTEC-ESS-SAN-ADMIN.GG
      - NA\WindowsServer-Std.FullAdmin.UG
      - "{{ domain_name.split('.')[0] }}\\XO.STORAGE.ENG.LG"
      - NA\CVNASBACKUP.UG
      - NA\CVNASTARGET.UG
      - NA\xsWFAMSP
      - "{{ domain_name.split('.')[0] }}\\DataFull.LG"
    ontapi              : "{{ ontap_facts.ontap_version }}"
    https               : true
    validate_certs      : false
  connection            : local

- name: Remove member from CIFS local group
  na_ontap_cifs_local_group_member:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : absent
    vserver             : "{{ svm_name | lower }}"
    group               : BUILTIN\Administrators
    member              : "{{ domain_name.split('.')[0] }}\\Domain Admins"
    ontapi              : "{{ ontap_facts.ontap_version }}"
    https               : true
    validate_certs      : false
  connection            : local