
- name: Add P-UTEC in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "UPSTREAMACCTS\\P-UTEC-ESS-SAN-ADMIN.GG"
    applications        : [ ontapi, ssh, http ]
    authentication_method: domain
    role_name           : admin
    vserver             : "{{ cluster_name | upper }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add XO Storage in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "{{ domain_name.split('.')[0] | upper }}\\XO.STORAGE.ENG.LG"
    applications        : [ ontapi, ssh, http ]
    authentication_method: domain
    role_name           : admin
    vserver             : "{{ cluster_name | upper }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add OCI ID in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "NA\\xsOnCommandInsight"
    applications        : ontapi
    authentication_method: domain
    role_name           : readonly
    vserver             : "{{ cluster_name | upper }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add TCP-OCI in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "NA\\xstcpoci"
    applications        : ssh
    authentication_method: domain
    role_name           : readonly
    vserver             : "{{ cluster_name | upper }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add XO Storage in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "NA\\TC.STORAGE.ENG.GG"
    applications        : [ ontapi, ssh, http ]
    authentication_method: domain
    role_name           : readonly
    vserver             : "{{ cluster_name | upper }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Add Splunk ID in Security Login - Security Model
  na_ontap_user:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "UPSTREAMACCTS\\xsSplunk-NetAppID"
    applications        : ontapi
    authentication_method: domain
    role_name           : readonly
    vserver             : "{{ cluster_name | upper }}"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
