---
# This code developed by Zura

- name: Create New VLAN Interface 2 on Node A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-01 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create New VLAN Interface 2 on Node B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port vlan create -node {{ cluster_name | upper }}-02 -vlan-name a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create Broadcast Domain for VLAN 2
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'network port broadcast-domain create -broadcast-domain {{ failover_group }} -mtu 1500 -ports {{ cluster_name | upper }}-01:a0a-{{ vlan2 }}, {{ cluster_name | upper }}-02:a0a-{{ vlan2 }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create CIFS SVM
  na_ontap_svm:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    name                : "{{ svm_name | lower }}"
    root_volume         : "{{ svm_name | lower }}_root"
    root_volume_aggregate: "{{ aggr_a_data1 }}"
    root_volume_security_style: ntfs
    language            : C.UTF-8
    snapshot_policy     : default
    ipspace             : Default
    comment             : "CIFS File Share"
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create CIFS SVM MGMT LIF using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : ["network interface create -vserver {{ svm_name | lower }} -lif {{ svm_name | lower }}_mgmt -role data -data-protocol none -home-node {{ cluster_name | upper }}-01 -home-port a0a-{{ vlan2 }} -address {{ svm_ip_m }} -netmask {{ svm_netmask }} -status-admin up -failover-policy broadcast-domain-wide -firewall-policy mgmt -auto-revert true -failover-group {{ failover_group }}"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Configure CIFS SVM node A LIF using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "network interface create -vserver {{ svm_name | lower }} -lif {{ svm_name | lower }}_cifs_lif01 -role data -data-protocol cifs -address {{ svm_lif1_ip }} -netmask {{ svm_netmask }} -home-port a0a-{{ vlan2 }} -home-node {{ cluster_name | upper }}-01 -auto-revert true -failover-policy broadcast-domain-wide -firewall-policy data -failover-group {{ failover_group }} -status-admin up " ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Configure CIFS SVM node B LIF using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "network interface create -vserver {{ svm_name | lower }} -lif {{ svm_name | lower }}_cifs_lif02 -role data -data-protocol cifs -address {{ svm_lif2_ip }} -netmask {{ svm_netmask }} -home-port a0a-{{ vlan2 }} -home-node {{ cluster_name }}-02 -auto-revert true -failover-policy broadcast-domain-wide -firewall-policy data -failover-group {{ failover_group }} -status-admin up " ]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
