---
# Test code join Domain

- name: Setup CIFS using CLI
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "vserver cifs create -vserver {{ svm_name }} -cifs-server {{ svm_name | upper }} -domain {{ domain_name }} -ou OU=NTAP,OU=\"Standard Servers\" -status-admin up"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Setup CIFS using CLI
  na_ontap_command:
    command             : [ "{{ domain_login }}"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Setup CIFS using CLI
  na_ontap_command:
    command             : [ "{{ domain_pwd }}"]
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local


# - name: Create cifs_server
#   na_ontap_cifs_server:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     state               : present
#     name                : "{{ svm_name | upper }}"
#     vserver             : "{{ svm_name }}"
#     service_state       : started
#     domain              : "{{ domain_name }}"
#     ou                  : OU=NTAP,OU="Standard Servers"
#     admin_user_name     : "{{ domain_login }}"
#     admin_password      : "{{ domain_pwd }}"
#     force               : yes
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local
