
- name: Create cifs_server
  na_ontap_cifs_server:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    cifs_server_name    : "{{ svm_name | upper }}"
    vserver             : "{{ svm_name | lower }}"
    service_state       : started
    domain              : "{{ domain_name }}"
    ou                  : OU=NTAP,OU="Standard Servers"
    admin_user_name     : "{{ domain_login }}"
    admin_password      : "{{ domain_pwd }}"
    force               : yes
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local
