---
# This code developed by NZABDU

- name: Create FlexVol on Node A
  na_ontap_volume:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    vserver             : "{{ svm_name | lower }}"
    name                : "{{ svm_name | lower }}_root_ls01"
    aggregate_name      : "{{ aggr_a_data1 }}"
    size                : 1
    size_unit           : gb
    type                : DP
    space_guarantee     : none
    policy              : default
    wait_for_completion : true
    comment             : ansible created LS volume
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create FlexVol on Node B
  na_ontap_volume:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    state               : present
    vserver             : "{{ svm_name | lower }}"
    name                : "{{ svm_name | lower }}_root_ls02"
    aggregate_name      : "{{ aggr_b_data1 }}"
    size                : 1
    size_unit           : gb
    type                : DP
    space_guarantee     : none
    policy              : default
    wait_for_completion : true
    comment             : ansible created LS volume
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create snapmirror for LS A
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "snapmirror create -source-path {{ svm_name | lower }}:{{ svm_name | lower }}_root -destination-path {{ svm_name | lower }}:{{ svm_name | lower }}_root_ls01 -type LS -schedule 5min" ] 
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Create snapmirror for LS B
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "snapmirror create -source-path {{ svm_name | lower }}:{{ svm_name | lower }}_root -destination-path {{ svm_name | lower }}:{{ svm_name | lower }}_root_ls02 -type LS -schedule 5min" ] 
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

- name: Initialize snapmirror for SVM
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ "snapmirror initialize-ls-set -source-path {{ svm_name | lower }}:{{ svm_name | lower }}_root" ] 
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local