
- name: Create User Role with access ALL
  na_ontap_user_role:
    state: present
    name: nfs_admin
    command_directory_name: 
      - security login role show-user-capability
      - security login role show-ontapi
      - vserver cifs
      - vserver export-policy
      - vserver nfs
      - vserver services
    access_level: all
    vserver: "{{ svm_name | lower }}"
    hostname: "{{ cluster_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create User Role with access READONLY
  na_ontap_user_role:
    state: present
    name: nfs_admin
    command_directory_name: 
      - dashboard health vserver
      - network interface
      - vserver
      - volume
    access_level: readonly
    vserver: "{{ svm_name | lower }}"
    hostname: "{{ cluster_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Create User Role with access NONE
  na_ontap_user_role:
    state: present
    name: nfs_admin
    command_directory_name: 
      - vserver fcp
      - vserver iscsi
      - vserver services name-service ldap
      - vserver services name-service unix-group max-limit
      - vserver services name-service unix-user max-limit
      - vserver services ndmp
      - vserver services web
    access_level: none
    vserver: "{{ svm_name | lower }}"
    hostname: "{{ cluster_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"

- name: Add Unix GG in security login
  na_ontap_command:
    hostname            : "{{ cluster_name }}"
    username            : "{{ netapp_username }}"
    password            : "{{ netapp_password }}"
    command             : [ 'security login create -user NA\NA.UnixServers.Ops.GG -auth domain -role nfs_admin -app ssh -vserver {{ svm_name | lower }}']
    ontapi              : 32
    https               : true
    validate_certs      : false
  connection            : local

# - name: Create NFS role 1
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [ 'security login role create -role nfs_admin -vserver {{ svm_name }} -access all -cmddirname "security login role show-user-capability"']
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local

# - name: Create NFS role 2
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [ 'security login role create -role nfs_admin -vserver {{ svm_name }} -access all -cmddirname "security login role show-ontapi" ']
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local

# - name: Create NFS role 3
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [ 'security login role create -role nfs_admin -vserver {{ svm_name }} -access all -cmddirname "vserver cifs" ']
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local

# - name: Create NFS role 4
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [ 'security login role create -role nfs_admin -vserver {{ svm_name }} -access all -cmddirname "vserver export-policy" ']
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local

# - name: Create NFS role 4
#   na_ontap_command:
#     hostname            : "{{ cluster_name }}"
#     username            : "{{ netapp_username }}"
#     password            : "{{ netapp_password }}"
#     command             : [ 'security login role create -role nfs_admin -vserver {{ svm_name }} -access all -cmddirname "vserver export-policy" ']
#     ontapi              : 32
#     https               : true
#     validate_certs      : false
#   connection            : local